# Generated by Django 2.2.5 on 2021-12-15 09:20
from django.core.management import call_command
from django.db import migrations


def load_fixture(apps,schema_editor):
    call_command('loaddata','blog/fixture/fixture.json',app_label="blog")

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211212_1611'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
